add: test img and some fix

diff --git a/tess b/tess
--- a/tess
+++ b/tess
@@ -1,9 +1,12 @@
 #!/usr/bin/env -S bash -e
 
-[ "$#" -eq 1 ] || {
-  echo "Usage: $0 <image path>">&2
+[ "$#" -lt 3 ] || {
+  echo "Usage: $0 <image path> [model]">&2
   exit 1
 }
+
+FILENAME="$1"
+MODEL="${2-jpn}"
 
 [ "$(tesseract -v 2>/dev/null|head -1|sed 's/^tesseract .*$/e/')" = "e" ] || {
   sudo add-apt-repository ppa:alex-p/tesseract-ocr -y
@@ -16,12 +19,14 @@
   sudo apt install tesseract-ocr-script-jpan tesseract-ocr-script-jpan-vert
 }
 
-[ -f "$1" ] || {
-  echo "Error: '$1' is not found">&2
+[ -f "$FILENAME" ] || {
+  echo "Error: '$FILENAME' is not found">&2
   exit 1
 }
+echo "#[picture]: $FILENAME"
+echo "#[model]:   $MODEL"
 echo "#[test: command]"
-tesseract "$1" stdout -l jpn
+tesseract "$FILENAME" stdout -l "$MODEL"
 
 echo "#[test: python]"
 python -m pip install -U pytesseract Pillow opencv-python -q
@@ -32,9 +37,12 @@ from PIL import Image
 from pprint import pprint
 import pytesseract
 
-FILENAME = "$1"
+FILENAME = "$FILENAME"
+MODEL = "$MODEL"
 im = cv2.imread(FILENAME)
-d = pytesseract.image_to_data(im, output_type=pytesseract.Output.DICT)
+d = pytesseract.image_to_data(im, lang=MODEL,
+                              output_type=pytesseract.Output.DICT)
+print(d["text"])
 
 for i in range(len(d['level'])):
     x, y = d['left'][i], d['top'][i]
